# Generated by Django 4.2.5 on 2023-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note', models.CharField(default='', max_length=2000)),
                ('date_at', models.DateTimeField(auto_now_add=True)),
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
